name: Java CI

on:
    push:
        branches: [ master ]

jobs:
    build-and-analyze:
        strategy:
            matrix:
                os: [ ubuntu-latest ]
                java: [ 17, 8 ]
            fail-fast: false

        runs-on: ${{ matrix.os }}

        name: Build and Run Sonar analysis on JDK 17
        steps:
            -   name: Checkout Code
                uses: actions/checkout@v3
                with:
                    # Disabling shallow clone for improving relevancy of SonarQube reporting
                    fetch-depth: 0

            -   name: Set up cache for ~./m2/repository
                uses: actions/cache@v3
                with:
                    path: ~/.m2/repository
                    key: maven-${{ matrix.os }}-java${{ matrix.java }}-${{ hashFiles('**/pom.xml') }}
                    restore-keys: |
                        maven-${{ matrix.os }}-java${{ matrix.java }}-
                        maven-${{ matrix.os }}-

            -   name: Install Toolchain JDK
                if: ${{ matrix.java == '17' }}
                uses: battila7/jdk-via-jabba@v1
                with:
                    java-version: '8'
                    distribution: 'temurin'
                    targets: 'TOOLCHAIN_JDK'
                    javaHomeEnvironmentVariable: TOOLCHAIN_JDK

            -   name: Set up Toolchain
                if: ${{ matrix.java == '17' }}
                shell: bash
                run: |
                    mkdir -p $HOME/.m2 \
                    && cat << EOF > $HOME/.m2/toolchains.xml
                    <?xml version="1.0" encoding="UTF8"?>
                    <toolchains>
                        <toolchain>
                            <type>jdk</type>
                            <provides>
                                <version>1.8</version>
                                <vendor>temurin</vendor>
                            </provides>
                            <configuration>
                                <jdkHome>${{ env.TOOLCHAIN_JDK }}</jdkHome>
                            </configuration>
                        </toolchain>
                    </toolchains>
                    EOF

            -   name: Set up JDK 17
                uses: actions/setup-java@v3
                with:
                    distribution: 'temurin'
                    java-version: ${{ matrix.java }}
                    cache: 'maven'

            # Cache Sonar packages which as used to run analysis and collect metrics
            -   name: Cache SonarCloud packages
                uses: actions/cache@v3
                with:
                    path: ~/.sonar/cache
                    key: ${{ runner.os }}-sonar
                    restore-keys: ${{ runner.os }}-sonar

            # Some tests need screen access
            -   name: Install xvfb
                run: sudo apt-get install -y xvfb

            -   name: Build with Maven and run SonarQube analysis
                run: xvfb-run ./mvnw -B clean verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=tu-yucheng_taketoday-tutorial4j -Dsonar.organization=tuyucheng -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=${{ secrets.SONAR_TOKEN }} -Pfirst-all,second-all,heavy-all
                env:
                    # These two env variables are needed for sonar analysis
                    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                    SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}